export enum Colors {
  PRIMARY = 'primary',
  ACCENT = 'accent',
  TEXT100 = 'text100',
  TEXT75 = 'text75',
  TEXT50 = 'text50',
  TEXT25 = 'text25',
  NEUTRAL1 = 'neutral1',
  NEUTRAL2 = 'neutral2',
  NEUTRAL3 = 'neutral3',
  SURFACE0 = 'surface0',
  SURFACE1 = 'surface1',
  GRADIENT1_START = 'gradient1Start',
  GRADIENT1_END = 'gradient1End',
  GRADIENT2_START = 'gradient2Start',
  GRADIENT2_END = 'gradient2End',
  GRADIENT3_START = 'gradient3Start',
  GRADIENT3_END = 'gradient3End',
}

export enum Dimensions {
  D2 = 'd2',
  D4 = 'd4',
  D8 = 'd8',
  D16 = 'd16',
  D24 = 'd24',
  D32 = 'd32',
  D40 = 'd40',
  D56 = 'd56',
  R4 = 'r4',
  R8 = 'r8',
  R16 = 'r16',
  ICON_SMALL = 'iconSmall',
  ICON_MEDIUM = 'iconMedium',
  ICON_LARGE = 'iconLarge',
  BORDER_SMALL = 'borderSmall',
  BORDER_MEDIUM = 'borderMedium',
  BORDER_LARGE = 'borderLarge',
}
